spring:
  application:
    name: crud-tareas

datasource:
  customs:
    query-timeout: 20
  my-connection:
    jdbc-url: jdbc:postgresql://localhost:5432/os_systems
    username: admin
    password: 12345
    maximum-pool-size: 10
    pool-name: "crud-pool"
    auto-commit: true